FROM rust:latest

RUN cargo install --version='~0.8' sqlx-cli --no-default-features --features rustls,postgres

RUN apt-get update && \
    apt-get install -y bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workflow

COPY ./scripts .
ADD migrations ./migrations

CMD ["./init_db.sh"]