-- Create Subscription Tokens Table
CREATE TABLE subscription_tokens(
   subscription_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   subscription_token VARCHAR(256) NOT NULL UNIQUE,
   subscriber_id BIGINT NOT NULL
      REFERENCES subscriptions (id) ON DELETE CASCADE,
   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
