-- Create Subscriptions Table
CREATE TABLE subscriptions (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   email TEXT NOT NULL UNIQUE,
   name TEXT NOT NULL,
   subscribed_at TIMESTAMPTZ NOT NULL
);
