CREATE TYPE subscription_status_enum AS ENUM('pending_confirmation', 'confirmed');

-- Create Subscriptions Table
CREATE TABLE subscriptions (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   email VARCHAR(256) NOT NULL UNIQUE,
   name VARCHAR(256) NOT NULL,
   subscribed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
   subscription_status subscription_status_enum NOT NULL DEFAULT 'pending_confirmation'
);
